services:
  - type: web
    name: github-mcp-server
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /healthz
    autoDeploy: true
    dockerCommand: http --base-url https://github-mcp-server-ix19.onrender.com
    envVars:
      - key: GITHUB_HOST
        value: github.com
